name: mobile
description: A checkout page.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flip_card: ^0.4.4
  intl: ^0.16.1
  flutter_cupertino_date_picker: ^1.0.26+2
  flare_flutter: ^2.0.5

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - flare/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Thin.ttf
          weight: 100
        - asset: fonts/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: fonts/RobotoMono-Light.ttf
          weight: 300
        - asset: fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: fonts/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700